name: good_dismissable
description: Good Dismissable
version: 1.0.0
homepage: https://github.com/ZianFahrudy/good_dismissable

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
